// <auto-generated />
using System;
using ECommerce.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625081512_InitialSetupClean")]
    partial class InitialSetupClean
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Domain.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_CartItems_Quantity_Positive", "`Quantity` > 0");
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ShippingAddressLine1")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("ShippingAddressLine2")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ShippingCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ShippingFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ShippingPostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_Orders_TotalAmount_NonNegative", "`TotalAmount` >= 0");
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ProductSkuSnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPriceSnapshot")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderItems_Quantity_Positive", "`Quantity` > 0");

                            t.HasCheckConstraint("CK_OrderItems_UnitPriceSnapshot_NonNegative", "`UnitPriceSnapshot` >= 0");
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products", null, t =>
                        {
                            t.HasCheckConstraint("CK_Products_Price_NonNegative", "`Price` >= 0");

                            t.HasCheckConstraint("CK_Products_StockQuantity_NonNegative", "`StockQuantity` >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Over-ear noise-cancelling headphones with 30-hour battery life.",
                            ImageUrl = "https://images.unsplash.com/photo-1505740420928-5e560c06d30e",
                            IsActive = true,
                            Name = "Wireless Bluetooth Headphones",
                            Price = 59.99m,
                            Sku = "ELEC-WH-001",
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tracks heart rate, steps, and sleep with a 7-day battery.",
                            ImageUrl = "https://picsum.photos/seed/elec-sw-002/400/400",
                            IsActive = true,
                            Name = "Smart Fitness Watch",
                            Price = 89.99m,
                            Sku = "ELEC-SW-002",
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 3,
                            Description = "Brew up to 12 cups with a 24-hour programmable timer.",
                            ImageUrl = "https://picsum.photos/seed/home-cm-003/400/400",
                            IsActive = true,
                            Name = "12-Cup Programmable Coffee Maker",
                            Price = 45.50m,
                            Sku = "HOME-CM-003",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 4,
                            Description = "1200W motor with 6 stainless steel blades for smoothies.",
                            ImageUrl = "https://picsum.photos/seed/home-bl-004/400/400",
                            IsActive = true,
                            Name = "High-Speed Countertop Blender",
                            Price = 69.99m,
                            Sku = "HOME-BL-004",
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 5,
                            Description = "Extra-thick 6mm eco-friendly TPE yoga mat with carrying strap.",
                            ImageUrl = "https://picsum.photos/seed/sprt-ym-005/400/400",
                            IsActive = true,
                            Name = "Non-Slip Yoga Mat",
                            Price = 24.99m,
                            Sku = "SPRT-YM-005",
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 6,
                            Description = "Pair of adjustable dumbbells for home strength training.",
                            ImageUrl = "https://picsum.photos/seed/sprt-db-006/400/400",
                            IsActive = true,
                            Name = "Adjustable Dumbbell Set 20lb",
                            Price = 79.99m,
                            Sku = "SPRT-DB-006",
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 7,
                            Description = "Stainless steel knives with wooden block and built-in sharpener.",
                            ImageUrl = "https://picsum.photos/seed/ktch-ks-007/400/400",
                            IsActive = true,
                            Name = "15-Piece Kitchen Knife Set",
                            Price = 54.99m,
                            Sku = "KTCH-KS-007",
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 8,
                            Description = "Oil-free frying with 8 preset cooking programs.",
                            ImageUrl = "https://picsum.photos/seed/ktch-af-008/400/400",
                            IsActive = true,
                            Name = "Digital Air Fryer 5.8QT",
                            Price = 64.99m,
                            Sku = "KTCH-AF-008",
                            StockQuantity = 0
                        },
                        new
                        {
                            Id = 9,
                            Description = "Bestselling mystery novel, paperback edition.",
                            ImageUrl = "https://picsum.photos/seed/book-nv-009/400/400",
                            IsActive = true,
                            Name = "\"The Last Lighthouse\" Novel",
                            Price = 14.99m,
                            Sku = "BOOK-NV-009",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 10,
                            Description = "Creative building blocks compatible with major brands.",
                            ImageUrl = "https://picsum.photos/seed/toys-lb-010/400/400",
                            IsActive = true,
                            Name = "500-Piece Building Block Set",
                            Price = 34.99m,
                            Sku = "TOYS-LB-010",
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 11,
                            Description = "Fast-charging power bank with dual USB-C ports.",
                            ImageUrl = "https://picsum.photos/seed/elec-pb-011/400/400",
                            IsActive = true,
                            Name = "20000mAh Portable Power Bank",
                            Price = 29.99m,
                            Sku = "ELEC-PB-011",
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 12,
                            Description = "Lightweight cordless vacuum with HEPA filter.",
                            ImageUrl = "https://picsum.photos/seed/home-vc-012/400/400",
                            IsActive = true,
                            Name = "Cordless Stick Vacuum Cleaner",
                            Price = 129.99m,
                            Sku = "HOME-VC-012",
                            StockQuantity = 9
                        },
                        new
                        {
                            Id = 13,
                            Description = "Lightweight expandable hose with 8-pattern spray nozzle.",
                            ImageUrl = "https://picsum.photos/seed/gard-hs-013/400/400",
                            IsActive = true,
                            Name = "50ft Expandable Garden Hose",
                            Price = 32.99m,
                            Sku = "GARD-HS-013",
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 14,
                            Description = "Memory foam dog bed with removable, washable cover.",
                            ImageUrl = "https://picsum.photos/seed/pets-db-014/400/400",
                            IsActive = true,
                            Name = "Orthopedic Dog Bed (Large)",
                            Price = 49.99m,
                            Sku = "PETS-DB-014",
                            StockQuantity = 14
                        },
                        new
                        {
                            Id = 15,
                            Description = "Adjustable lumbar support office chair with breathable mesh back.",
                            ImageUrl = "https://picsum.photos/seed/offc-ch-015/400/400",
                            IsActive = true,
                            Name = "Ergonomic Mesh Office Chair",
                            Price = 149.99m,
                            Sku = "OFFC-CH-015",
                            StockQuantity = 6
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
